CREATE SCHEMA IF NOT EXISTS "notification";

CREATE TABLE IF NOT EXISTS "notification"."telegram_user" (
  "id" int PRIMARY KEY,
  "name" varchar,
  "created_at" timestamp default now(),
  "updated_at" timestamp default CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "notification"."telegram_notification" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "value" text,
  "schedule" varchar(256),
  "created_at" timestamp default now(),
  "updated_at" timestamp default CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "user_id" ON "notification"."telegram_notification" ("user_id");
COMMENT ON COLUMN "notification"."telegram_notification"."user_id" 
	IS 'See notification.telegram_user.id';
COMMENT ON COLUMN "notification"."telegram_notification"."schedule" 
	IS 'Unix cron schedule format';
