version: '3.5'

services:
  app:
    build:
      context: .
    container_name: tg-scheduler
    ports:
      - 4000:4000
    deploy:
      restart_policy:
        condition: on-failure
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    deploy:
      restart_policy:
        condition: on-failure
