version: '3.5'

services:
  app:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    volumes:
      - /home/aleksandr/redis/conf:/usr/local/etc/redis
      - /home/aleksandr/redis/data:/data
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - tg_scheduler
networks:
  tg_scheduler:
    name: tg_scheduler
    driver: bridge
