version: "3.3"

services: 
        nginx:
                image: nginx
                volumes: 
                        - ./templates:/etc/nginx/templates
                        - ./cert:/etc/ssl
                ports:
                        - "80:80"
                        - "443:443"
                environment:
                        - NGINX_PORT=80
                extra_hosts:
                        - "host.docker.internal:host-gateway"
