version: '3.5'

services:
  app:
    image: furken142/tg:v0.0.7
    container_name: tg-scheduler
    ports:
      - 4000:4000
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - tg_scheduler
networks:
  tg_scheduler:
    name: tg_scheduler
    driver: bridge
