---
# ansible-playbook -e @secrets.yaml --ask-vault-pass build.yaml
- name: execute migrations
  hosts: hetzner
  gather_facts: no

  vars: 
    migration_path: /home/aleksandr/postgres/migrations
  tasks:
    - name: create dirs for migrations
      shell: |
        mkdir -p '{{ migration_path }}'
    - name: copy migrations
      copy:
        src: ../db/migrations
        dest: /home/aleksandr/postgres
    - name: define postgres host
      command: docker container inspect -f {%raw%}'{{ .NetworkSettings.Networks.tg_scheduler.IPAddress }}'{%endraw%} postgres
      register: postgres_host_raw

    - name: extract postgres host
      set_fact:
        postgres_host: "{{ postgres_host_raw.stdout_lines[0] }}"

    - name: execute migrations
      shell: |
       migrate -path '{{ migration_path }}' -database "postgresql://{{postgres_user}}:{{postgres_password}}@{{ postgres_host }}:5432/tg_scheduler?sslmode=disable" -verbose up 1
